#!/bin/sh
##
## frequent_itemset_basic.sh
## 
## Made by Benjamin Negrevergne
## Login   <bengreve@neb.imag.fr>
## 
## Started on  Wed Oct 20 09:53:09 2010 Benjamin Negrevergne
## Last update Wed Oct 20 09:53:09 2010 Benjamin Negrevergne
##

#check if the number of patterns generated by clogen is equal the the number of patterns generated by lcm
#usage is : ./frequent_itemset_basic dataset minsup [nbthreads=1]

usage(){
echo "./frequent_itemset_basic dataset minsup [nbthreads=1]" 
exit
}

if [ $# -lt 2 ]; then usage; fi

if [ $# -eq 2 ]; then NUM_THREAD="1"; else NUM_THREAD=$3; fi


NB_PAT_CLOGEN=$(../clogen_itemsets $1 $2 -t $NUM_THREAD |grep "patterns mined"|cut -d " " -f 1)
NB_PAT_LCM=$(../fim_closed $1 $2 | head -n 1)

test $NB_PAT_CLOGEN -eq $NB_PAT_LCM