#!/bin/sh
##
## grad_glcm_full.sh
## 
## Made by Benjamin Negrevergne
## Login   <bengreve@neb.imag.fr>
## 
## Started on  Thu Feb  3 18:33:35 2011 Benjamin Negrevergne
## Last update Thu Feb  3 18:33:35 2011 Benjamin Negrevergne
##

# Sort and compare graduals pattern generated by clogen with theses generated by glcm. 
# (One by one !)

external/glcm/glcm nor ../data/graduals/test1.data $1 | ./sort_line_grads.pl > /tmp/glcm_tmp1
../src/clogen_graduals ../data/graduals/test1.data $1 | ./sort_line_grads.pl > /tmp/clogen_tmp1

diff /tmp/glcm_tmp1 /tmp/clogen_tmp1