#!/bin/sh
##
## frequent_itemset_basic.sh
## 
## Made by Benjamin Negrevergne
## Login   <bengreve@neb.imag.fr>
## 
## Started on  Wed Oct 20 09:53:09 2010 Benjamin Negrevergne
## Last update Wed Oct 20 09:53:09 2010 Benjamin Negrevergne
##

#check if the number of patterns generated by clogen is equal the the number of patterns generated by lcm
#usage is : ./frequent_itemset_basic dataset minsup [nbthreads=1]

usage(){
echo "./frequent_itemset_basic dataset minsup [nbthreads=1]" 
exit
}

if [ $# -lt 2 ]; then usage; fi

if [ $# -eq 2 ]; then NUM_THREAD="1"; else NUM_THREAD=$3; fi

PARAMINER_FIM="../src/clogen_itemsets"
LCM_FIM="./external/lcm25/fim_closed" 

CMD_LINE="$PARAMINER_FIM $1 $2 -t $NUM_THREAD"
echo "CMD : >$CMD_LINE<"
NB_PAT_CLOGEN=$($CMD_LINE |grep "patterns mined"|cut -d " " -f 1)

CMD_LINE="$LCM_FIM $1 $2 -t $NUM_THREAD"
echo "CMD : >$CMD_LINE<"
NB_PAT_LCM=$($LCM_FIM $1 $2 | head -n 1)

echo "NUM PAT PARAMINER: $NB_PAT_CLOGEN NUM PAT LCM: $NB_PAT_LCM"
test $NB_PAT_CLOGEN -eq $NB_PAT_LCM